import { useWorkspace } from "@/contexts/WorkspaceContext";
import { ChevronDown, Plus } from "lucide-react";
import { useState } from "react";

export function WorkspaceSwitcher() {
  const { workspaces, projects, activeWorkspace, activeProject, loading, setActiveWorkspace, setActiveProject, createWorkspace, createProject } = useWorkspace();
  const [open, setOpen] = useState(false);
  return <div className="relative"><p className="swan-eyebrow">Workspace</p><button type="button" onClick={() => setOpen((value) => !value)} className="mt-2 flex w-full items-center justify-between border border-black bg-white px-3 py-2.5 text-left transition-colors hover:bg-black hover:text-white"><span className="truncate text-sm font-semibold tracking-[-0.02em]">{loading ? "Loading…" : activeWorkspace?.name ?? "Create workspace"}</span><ChevronDown className="size-4 shrink-0"/></button>{open && <div className="absolute left-0 right-0 z-50 mt-1 border border-black bg-white p-1 shadow-[5px_5px_0_#e11d1d]"><div className="max-h-44 overflow-auto">{workspaces.map((workspace) => <button type="button" key={workspace.id} onClick={() => { setActiveWorkspace(workspace); setOpen(false); }} className={`block w-full px-3 py-2 text-left text-sm hover:bg-black hover:text-white ${activeWorkspace?.id === workspace.id ? "bg-black text-white" : ""}`}>{workspace.name}<span className="ml-2 font-mono text-[9px] uppercase opacity-60">{workspace.role}</span></button>)}</div><button type="button" onClick={() => { createWorkspace(); setOpen(false); }} className="mt-1 flex w-full items-center gap-2 border-t border-black px-3 py-2 font-mono text-[10px] uppercase tracking-[0.08em] hover:bg-red-600 hover:text-white"><Plus className="size-3"/> New workspace</button></div>}<p className="mt-3 swan-eyebrow">Project</p><div className="mt-2 flex gap-1"><select value={activeProject?.id ?? ""} onChange={(event) => setActiveProject(event.target.value ? projects.find((project) => project.id === Number(event.target.value)) ?? null : null)} disabled={!activeWorkspace || loading} className="h-9 min-w-0 flex-1 border border-black bg-white px-2 font-mono text-[10px] uppercase tracking-[0.07em]"><option value="">{activeWorkspace ? "No project" : "Select workspace"}</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><button type="button" onClick={createProject} disabled={!activeWorkspace} className="grid size-9 place-items-center border border-black bg-white hover:bg-black hover:text-white disabled:opacity-30" aria-label="Create project"><Plus className="size-3.5"/></button></div></div>;
}
